### ISSUE TITLE
The function 'Redefine_nn' doesn't make the network follow LRP rule

### ISSUE THREAD

**Issue by explorationRoad** [dreizehnutters/pcapAE#4]
![Snipaste_2024-05-28_13-19-14](https://github.com/dreizehnutters/pcapAE/assets/162122866/1def7466-a20b-4455-a5b2-3b0393480349)
When I debug the program, I find that whether I comment out the below code or not
![Snipaste_2024-05-28_13-27-40](https://github.com/dreizehnutters/pcapAE/assets/162122866/b0c4e593-252a-4e76-b430-5ca1b1df45b2)
I got the same relevance in the function 'relprop'
![Snipaste_2024-05-28_13-30-53](https://github.com/dreizehnutters/pcapAE/assets/162122866/e5fe7333-deca-41a3-a5e3-624654da20cc)
But this result doesn't meet the expectation, which we will get different relevance after redefining the network in terms of LRP rule. So I think the function 'redefine' doesn't work following expection.

**Comment by explorationRoad** [comment]
So in your master thesis, there exits some mistakes.

**Comment by explorationRoad** [comment]
So in your master thesis, there maybe exit some mistakes.

**Comment by explorationRoad** [comment]
The network follows the gradient rule, instead of LRP rule

**Comment by explorationRoad** [comment]
It's my honor to receive your response

**Comment by dreizehnutters** [comment]
Hello,

thanks for checking out my thesis projekt.

As i submitted the code over three years ago i cannot fully understand everything i did back then.

The LRP part added last and helped me get some insight into the model. Compare chapter 6.3 of my [paper](https://arxiv.org/pdf/2205.08953#section.6.3) for more details.

And if you can improve upon my work, please dont hesitate to make a pull request.
